### ISSUE TITLE
Add generic profiling information (CrayPat))

### ISSUE THREAD

**Issue by lcebaman** [ARCHER2-HPC/archer2-docs#10]

**Comment by lcebaman** [comment]
Yes, the idea was to cover CrayPat-lite and CrayPat with what we know already.

**Comment by lcebaman** [comment]
@aturner-epcc I've got some basic profiling documentation using CrayPat-lite and CrayPat. Harvey mentioned that there is something new called ```patrun``` which we could not play with it until the TDS is operative. Do you want me to open a pull request with what I have at the moment or wait until the TDS is available?

**Comment by aturner-epcc** [comment]
@lcebaman Thanks. I think you should issue a PR and get in the stuff you have now and then we can modify as required once we know more.

**Comment by aturner-epcc** [comment]
Done in #31
