### ISSUE TITLE
Document use of hybrid MPI+OpenMP

### ISSUE THREAD

**Issue by aturner-epcc** [ARCHER2-HPC/archer2-docs#107]
The current documentation has an example MPI+OpenMP script but no documentation describing the background of how to run these jobs, more advanced placement information and a description of the best layout to match onto the ARCHER2 NUMA structure. This should be added in the Scheduler chapter. Point to the Tuning chapter for more advanced information on OpenMP.

**Comment by kevinstratford** [comment]
This is covered at
https://docs.archer2.ac.uk/user-guide/scheduler/#example-job-submission-script-for-mpiopenmp-mixed-mode-parallel-job
