### ISSUE TITLE
Update NAMD page with information on how to get good performance

### ISSUE THREAD

**Issue by aturner-epcc** [ARCHER2-HPC/archer2-docs#108]
Early access users identified that particular run options and configuration are required to get good performance using NAMD on ARCHER2. The NAMD page needs to be updated to include this information.

**Comment by kevinstratford** [comment]
This is covered in
https://docs.archer2.ac.uk/research-software/namd/namd/

**Comment by kevinstratford** [comment]
Closed at PR184
