### ISSUE TITLE
Initial version of Python chapter

### ISSUE THREAD

**Issue by aturner-epcc** [ARCHER2-HPC/archer2-docs#13]
Before we can update the Python chapter, we need to decide on the approach to Python on ARCHER2. Initial proposal is:

* For compute node, high-performance Python: use the cray-python environment. Need to document how you use this and how you install further Python modules on top
* For data analysis, serial Python: probably provide an Anaconda distribution. Should this be provided as a module or a container environment?
* For self-installed Python: need to recommend a solution. Could be miniconda or could advise to pull containers from the DockerHub

**Comment by markgbeckett** [comment]
I wonder if, in fact, this should be two sections, with the data analysis stuff being folder into a different section and this section focusing on Python for computation?

**Comment by aturner-epcc** [comment]
@markgbeckett I am happy with this as long as it is well signposted in each of the relevant sections. We could put the data analysis bit in a Python subsection of the Data Analysis and Tools section.

**Comment by aturner-epcc** [comment]
@claoidek Can you have a go at putting in initial text for this section please? Initial focus on the HPC Python bit that will be based on the Cray Python distribution.

**Comment by AnnA227** [comment]
Will do

**Comment by claoidek** [comment]
Will do

**Comment by aturner-epcc** [comment]
Initial version in https://github.com/ARCHER2-HPC/archer2-docs/commit/5c5c059839679d65f0ba7e731e95a16a54eab99f#diff-ca050cc086e34ab6463b9063cb9016b0

**Comment by aturner-epcc** [comment]
Done in 5c5c059839679d65f0ba7e731e95a16a54eab99f

**Comment by aturner-epcc** [comment]
Done in 5c5c059839679d65f0ba7e731e95a16a54eab99f
