### ISSUE TITLE
Add information on connecting from Windows using command line rather than point and click GUI

### ISSUE THREAD

**Issue by aturner-epcc** [ARCHER2-HPC/archer2-docs#194]
At the moment we only cover connecting to ARCHER2 from Windows using MobaXTerm:

https://docs.archer2.ac.uk/user-guide/connecting/#logging-in-from-windows-using-mobaxterm

Now that Windows Powershell supports SSH command line more consistently we should update the docs to cover connecting using that mechanism from Windows too.

**Comment by aturner-epcc** [comment]
Other option is to document use of MobaXterm command line instead of point and click interface as CSE team members that use Windows say this works well.

**Comment by clairbarrass** [comment]
#215 was intended to resolve this issue

**Comment by aturner-epcc** [comment]
Thanks @clairbarrass . Closed this issue
