### ISSUE TITLE
Create initial entries in Data Analysis and Tools section

### ISSUE THREAD

**Issue by aturner-epcc** [ARCHER2-HPC/archer2-docs#241]
We need to look at creating some content here. Some initial pages could be:

* VisiData
* R (Cray R)

**Comment by markgbeckett** [comment]
Have provided very basic R page though, still to do:
 - [ ] Document how to access third-party R packages (that is packages not included in the HPE Cray installation).
 - [ ] Add an example of a parallel R script (assuming that makes sense).
