### ISSUE TITLE
List of Issues and Items for review prior to main system going live

### ISSUE THREAD

**Issue by clairbarrass** [ARCHER2-HPC/archer2-docs#279]
Review of ARCHER2 Docs and identifying issues with move to main system (7/ JUL/21)

- [x] Quickstart for developers #326 Kevin

 - [x] All known issues need review - https://docs.archer2.ac.uk/known-issues/index.html (GEORGE)

 - [x] Add information on using High Memory nodes - https://docs.archer2.ac.uk/faq/index.html#oom-error-on-archer2 (MICHAEL B)

 - [x] Check recommended IO file setting - https://docs.archer2.ac.uk/user-guide/io/ (DAVID H)

- [x] Check containers instructions stay the same https://docs.archer2.ac.uk/user-guide/containers/ (MICHAEL D)

- [x] Check python commands work - https://docs.archer2.ac.uk/user-guide/python/ (JULIEN S)

- [x] Add note on data visualisation nodes (DVN) - https://docs.archer2.ac.uk/user-guide/analysis/ (MICHAEL B)

- [x] check apprentice2 instructions works  + archer2jobload - https://docs.archer2.ac.uk/user-guide/profile/#cray-apprentice2
 (WILLIAM L)

- [x] Check version numbers - https://docs.archer2.ac.uk/user-guide/tuning/ (CODE CONTACTS)

- [x] Most will need an update including to check version numbers #283 #284 - https://docs.archer2.ac.uk/software-libraries [KEVIN  S]

- [x]  Most will need an update including to check version numbers - https://docs.archer2.ac.uk/data-tools/index.html (JULIEN S)

- [x] Get Crystal developers to check relevant documentation - https://docs.archer2.ac.uk/other-software/crystal/ (ANDY T, TBC)

### Changes completed

https://docs.archer2.ac.uk/faq/index.html#archer-work-data
Add year (2021) to date that ARCHER /work was decommissioned - DONE (CB)

https://docs.archer2.ac.uk/user-guide/connecting/#logging-in
Order of password and ssh key passphrase being reversed - DONE (ART)

https://docs.archer2.ac.uk/user-guide/data#work-file-systems - DONE (ART)
Update size to full /work 

https://docs.archer2.ac.uk/user-guide/sw-environment - DONE (ART)
@aturner-epcc to look at this. See: #301

https://docs.archer2.ac.uk/user-guide/scheduler/#quality-of-service-qos - DONE (ART)

https://docs.archer2.ac.uk/user-guide/scheduler/#using-modules-in-the-batch-system-the-epcc-job-env-module
Need to review whether epcc-job-env-module will continue
This may break every user submit script if changed! - DONE (ART)
@aturner-epcc to look at this

https://docs.archer2.ac.uk/user-guide/scheduler/#bolt-job-submission-script-creation-tool
*** Julien check if bolt works - DONE (ART)

https://docs.archer2.ac.uk/user-guide/dev-environment/
@aturner-epcc to look at this #302 - DONE (ART)

**Comment by welucas2** [comment]
I've reviewed the profiling documentation. Some small updates needed to be made and were found to apply also to the 4-cab, so I've made these changes in #281. `archer2jobload` is CSE software but will presumably work in the same way. Otherwise the profiling documentation should be ok.

**Comment by kevinstratford** [comment]
The branch for the updates is `archer-23`

**Comment by jsindt** [comment]
I checked that Python commands worker while still on system.

**Comment by davidhenty** [comment]
The parallel IO settings worked fine on the main system - I used those settings for my benchmark runs.

**Comment by aturner-epcc** [comment]
Please commit all changes for the full system documentation to the `full-system-initial-version` branch

**Comment by aturner-epcc** [comment]
Checked and closing
