### ISSUE TITLE
Add an example of how to use the Globus GridFTP client to transfer data to/ from ARCHER2

### ISSUE THREAD

**Issue by markgbeckett** [ARCHER2-HPC/archer2-docs#295]
Instructions in Data Management and Transfer say that parallel transfers are not supported, though do not show how to turn off parallel transfers (I'm not sure using '-p 1' will be sufficient). Also, it would be good to have a known-working testcase as the Globus clients tend to fall foul of firewalls, so users may see issues which may/ may not be specific to the server they are trying to contact.

**Comment by welucas2** [comment]
Discussions with @spbooth have indicated that parallel transfers should be feasible. However, a test case running on ARCHER2 copying to/from another system such as Cirrus will require the server to be installed and running there.

**Comment by aturner-epcc** [comment]
There are detailed instructions on how to use GridFTP to transfer from ARCHER2 to JASMIN at:

https://help.jasmin.ac.uk/article/4997-transfers-from-archer2

This will cover the vast majority of use cases on ARCHER2 so maybe we should just link to this in the section at:

https://docs.archer2.ac.uk/user-guide/data/#data-transfer-via-gridftp

**Comment by clairbarrass** [comment]
Done
