### ISSUE TITLE
Add note on cgroup control of login node resources

### ISSUE THREAD

**Issue by aturner-epcc** [ARCHER2-HPC/archer2-docs#345]
So that users are aware that one user cannot monopolise the login node and slow down response for other users

**Comment by holly-t** [comment]
@aturner-epcc Where in the docs do you think would be the best place to add this?

**Comment by aturner-epcc** [comment]
@holly-t Put it in the "Software Environment" section. Add a bit at the end after the "Shell Environment Overview" part
