### ISSUE TITLE
Add notes on underpopulation of nodes to make more memory available

### ISSUE THREAD

**Issue by aturner-epcc** [ARCHER2-HPC/archer2-docs#367]
The docs describe the options for setting process placement for the case when you are using processes+threads but do not really cover what placement you want when you are using pure (MPI) processes but want to underpopulate to gain more memory resources per process.

We need to clarify that you should use the `--cpus-per-task` option to set a suitable stride to ensure you distribute processes evenly across NUMA regions on a compute node.

**Comment by jsindt** [comment]
@aturner-epcc we can do this either by using `--distribution=block:cyclic` or by setting `--cpus-per-task`. I prefer the first solution because it distributes across NUMA regions without the need to calculate or specify a stride. Do you have any strong feelings either way?

**Comment by aturner-epcc** [comment]
I agree, this has the benefit that we can explain what the `--distribution` option to `srun` is doing
