### ISSUE TITLE
Approach to highlighting new known issues

### ISSUE THREAD

**Issue by d7919** [ARCHER2-HPC/archer2-docs#398]
Not sure if this is the correct place, but I was wondering if there is any policy on publicising new known issues amongst the Archer2 users. I've been digging into an intermittent out of memory issue off and on for a few weeks. I checked the known issues when the problem first appeared and there was nothing listed but I can now see that a likely issue and workaround was flagged a bit over a week ago. Would it be possible to include a summary of new known issues in the regular update emails to users? Is there already a mailing list for this that I should be signed up to?

**Comment by aturner-epcc** [comment]
@d7919 Thanks for highlighting this. There is no policy at the moment other than putting them up on the Known Issues page in the ARCHER2 documentation. However, I think your suggestion of highlighting any recently-added issues in the weekly update email is a good one and we will look to do this in the future. For the mailing next week, we will add an item reminding people that the Known Issues page is there and will say that we will include any new issues in future update mailings.
