### ISSUE TITLE
Refactor research software pages to rationalise URLs

### ISSUE THREAD

**Issue by aturner-epcc** [ARCHER2-HPC/archer2-docs#421]
Currently, the Research Software pages have URLS that look something like:

https://docs.archer2.ac.uk/research-software/castep/castep/

We should refactor the documentation to make these more sensible (and in line with, for example, the Software Libraries section), e.g. the URL above would become:

https://docs.archer2.ac.uk/research-software/castep/

The existing URL would continue to work but just contain a link back to the new URL.

**Comment by clairbarrass** [comment]
Closed by #423
