### ISSUE TITLE
MITgcm & OMP

### ISSUE THREAD

**Issue by fraserwg** [ARCHER2-HPC/archer2-docs#438]
There's currently no documentation on running MITgcm in hybrid MPI and OpenMP mode and I think we could do with adding some. I'm happy to give this a go having recently been playing around with hybrid applications.

In the meantime, would it be possible to add the line `OMPFLAG='-h omp'` in the file`/work/n02/shared/mjmn02/ECCOv4/cases/cce/cce1/scripts/dev_linux_amd64_cray_archer2` around line 18 (after the `NOOPTFILES=''` line). This should allow users to compile the model with omp when using the recommended options file.

**Comment by aturner-epcc** [comment]
Hi @fraserwg. Happy for you to contribute some docs here if you have experience with this.

I will contact the user who contributed the options file to ask them if they are happy to add the option for OpenMP.

**Comment by fraserwg** [comment]
Great - there's a pull request incoming

**Comment by MikeMineter** [comment]
Hi @fraserwg. 
You are right - the hybrid documentation does not exist.

That ....cce1,,, filepath will be removed from the documentation  once there is an options file merged with the MITgcm code, and this is being discussed in  https://github.com/MITgcm/MITgcm/pull/636

So what would be ideal (I think) is if you have successful tests of the hybrid mode on Archer2, we make changes to the documentation,  to reflect your knowledge on this

@DanJonesOcean is involved in this process of review and merge.

**Comment by aturner-epcc** [comment]
Thanks @MikeMineter

**Comment by DanJonesOcean** [comment]
Thanks for this. Just echoing @MikeMineter's suggestion that we should confirm that it has been tested.
