### ISSUE TITLE
Minor typo in priority description, worth reviewing details?

### ISSUE THREAD

**Issue by d7919** [ARCHER2-HPC/archer2-docs#476]
The description of the priority references Tursa rather than Archer2. I've raised an issue rather than providing a fix as it's possible the following description of the priority is also not accurate (although a quick check of /etc/slurm/slurm.conf suggests it is). 

https://github.com/ARCHER2-HPC/archer2-docs/blob/88cdc20c55c3e359baeb0de8ed6f1b145e3d2334/docs/user-guide/scheduler.md?plain=1#L255-L278

**Comment by aturner-epcc** [comment]
Good spot @d7919 . I have checked the details and fixed the typo.
