### ISSUE TITLE
Using mpi4py with UCX

### ISSUE THREAD

**Issue by mbareford** [ARCHER2-HPC/archer2-docs#557]
If one wishes to use UCX with the mpi4py provided by the cray-python module then one must load PrgEnv-gnu first.

module -q load PrgEnv-gnu
module -q load craype-network-ucx
module -q load cray-mpich-ucx
module -q load cray-python

Otherwise mpi4py will still be linked with the Cray MPICH OFI library and so complain about a missing libfabric library
(since the cray-mpich-ucx module unloads libfabric).

**Comment by aturner-epcc** [comment]
Note added to docs
