### ISSUE TITLE
Load PrgEnv-gnu when installing own packages

### ISSUE THREAD

**Issue by mbareford** [ARCHER2-HPC/archer2-docs#558]
In the "Installing your own Python packages (with pip)" section it is recommended that you should first do
"module load cray-python", but really, you should do "module load PrgEnv-gnu" before you load the cray-python module.

This is because subsequent pip installs may require source code compilation and it is better that this be done using the gcc compilers to maintain consistency with how existing python packages have been built.

Further, it may be necessary to prefix the pip install command with "CC=cc CXX=CC FC=ftn" to ensure that compilation is
done via the wrappers.

**Comment by aturner-epcc** [comment]
Note added to docs
