### ISSUE TITLE
Estimated run time

### ISSUE THREAD

**Issue by clairbarrass** [ARCHER2-HPC/archer2-docs#629]
Would be good to add info on how to see Estimated run time for a queued job, and to explain that this is dynamic and not a guarantee.
It comes up as a query moderately often.

**Comment by aturner-epcc** [comment]
We have documented a way to do this before the job is submitted:

https://docs.archer2.ac.uk/user-guide/scheduler/#checking-scripts-and-estimating-start-time-with-test-only

We should add notes on how to check estimated start time after the job has been submitted using squeue

**Comment by clairbarrass** [comment]
lgtm
